#!/usr/bin/env bash
#
# A set of common variables and functions.
#
# Author: James Mount
# Version: 0.2.0


#################
### VARIABLES ###
#################

# The location of the tools directory
TOOLS_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Screen Reset
RESET='\033[0m'

# Screen Colors
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"

# Screen helpers
INFO="${PURPLE}[INFO]${RESET} "
WARN="${YELLOW}[WARN]${RESET} "
ERROR="${RED}[ERROR]${RESET} "


#################
### FUNCTIONS ###
#################

function git_command_exists(){
    # Bail if git isn't found
    command -v git >& /dev/null || {
        printf "${ERROR}the 'git' command was not found, please install\n"
        exit 1
    }
}

function install_tool(){
    # Installs (git clones) the tools to a specified location, 
    # if the tool is not already installed. Will terminate
    # the program if failed to install.
    #
    # Usage:
    #   install_tool <INSTALL_DIR> <TOOLNAME>

    INSTALL_DIR=$1
    TOOL_NAME=$2

    # Clone repo if doesn't exist
    if [ ! -d "$INSTALL_DIR" ]; then
        printf "${INFO} No cached version of the '${TOOL_NAME}' tool found. Installing to '$INSTALL_DIR'...\n"
        mkdir -p "${INSTALL_DIR}"
        if ! git clone "$REPO_URL" "$INSTALL_DIR"; then
            printf "${ERROR} Install failed, please ensure machine has Internet access.\n"
            exit 1
        fi
    fi
    printf "\n"
}

function check_cloned_repo_is_latest(){
    # Check to see if a cloned repo is the latest. Will
    # print a warning if unable to check and state using the
    # cached version. Will tell the user to run an update if
    # using an outdated version.
    #
    # Usage:
    #   check_cloned_repo_is_latest <REPO_DIR> <TOOL_NAME>

    REPO_DIR=$1
    TOOL_NAME=$2

    # Check whether installed version is the latest (flagging if there are updates
    # available, or update check failed)
    latest="$(git -C "${REPO_DIR}" ls-remote 2>/dev/null | grep HEAD | cut -f 1 || true)"
    installed="$(git -C "$REPO_DIR" rev-parse HEAD)"
    if [ -z "$latest" ]; then
        printf "${WARN}check for latest tools failed; using cached version in '$REPO_DIR'.\n"
    elif [ "$latest" != "$installed" ]; then
        printf "${WARN}${YELLOW} - %s\n\t    %s\t%s\n\n${NORMAL}" \
        "Old version (${installed:0:8}) found in '$REPO_DIR'." \
        "Update to latest (${latest:0:8}) using:" \
        "qcr update ${TOOL_NAME} (not yet implemented)"
    fi
}