#!/usr/bin/env bash
#
# Points to https://github.com/qcr/code_templates/qcr_templates. This is
# deliberately light wrapper, so users can access the latest templates without
# every having to update. 
#
# Please see https://github.com/qcr/code_templates for full details on how
# things work, and instructions on how to add your own templates. The more
# templates the merrier!
#
# Author: Ben Talbot
# Version: 0.3.0

bash <(curl -s -L --compressed \
  https://raw.githubusercontent.com/qcr/code-templates/main/code-templates) "$@"
