#!/usr/bin/env bash
#
# A light wrapper for using the Commission tool via qcr command. 
# This is deliberately light, so that users should never 
# have to update this script once they have it, but will
# always have access to the latest service tool.
#
# It installs (git clones) the commission tool if it doesn't
# exist, and then calls the commission tool entry point script.
# Information on the commission tool can be found at:
#     https://github.com/qcr/qcr-commission-tools
# 
# For usage on how to use the commission tool run: 
#     qcr commission -h
#
# Author: James Mount
# Version: 0.2.0


#################
### VARIABLES ###
#################


# The URL for this tool's repo
# Used for cloning - Recommend to use SSH
REPO_CLONE_URL="git@github.com:qcr/commissioning-tool.git"

# Tool name - name of entry point script in the separate repo.
# The recommendation is the script here in qcr/scripts matches
# the name of the script in the separate repo. However,
# can change TOOL_NAME if they are different.
# TOOL_NAME="$(basename $(readlink -f $0))"
TOOL_NAME=install

# The directory of containing this script
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# The install directory to the tools directory
# INSTALL_DIR="$(dirname ${SCRIPT_DIR})/installed-tools/${TOOL_NAME}"
INSTALL_DIR="$(dirname ${SCRIPT_DIR})/installed-tools/commissioning-tool"


#################
### FUNCTIONS ###
#################



############
### MAIN ###
############

# Get arguments passed by qcr script, 
# Arguments passed are:
#   USE_CACHED
#   ARGS_TO_TOOL
USE_CACHED="${@:1:1}"
ARGS=( "${@:2}" )

# Source common
source $(dirname ${SCRIPT_DIR})/common

# Bail if git isn't found
git_command_exists

# Install tool, if required
install_tool ${REPO_CLONE_URL} ${INSTALL_DIR} ${TOOL_NAME}

# check if latest
if [ ${USE_CACHED} == false ]; then
    check_cloned_repo_is_latest ${INSTALL_DIR} ${TOOL_NAME}
fi
 
# Run commission-system tool with provided command and arguments
${INSTALL_DIR}/${TOOL_NAME}  "${ARGS[@]}"
