#!/usr/bin/env bash
#
# A light wrapper for using the <TOOL-NAME> tool via qcr command. 
# This is deliberately light, so that users should never 
# have to update this script once they have it, but will
# always have access to the latest service tool.
#
# It installs (git clones) the <TOOL-NAME> tool if it doesn't
# exist, and then calls the <TOOL-NAME> tool entry point script.
# Information on the <TOOL-NAME> tool can be found at:
#     https://github.com/qcr/<TOOL-NAME>
# 
# For usage on how to use the <TOOL-NAME> tool run: 
#     qcr <TOOL-NAME> -h
#
# Author: James Mount
# Version: 0.2.0


#################
### VARIABLES ###
#################


# The URL for this tool's repo 
# Used for cloning - Recommend to use SSH
REPO_CLONE_URL="git@github.com:qcr/<TOOL-NAME>"

# Tool name - name of entry point script in the separate repo.
# The recommendation is the script here in qcr/scripts matches
# the name of the script in the separate repo. However,
# can change TOOL_NAME if they are different.
TOOL_NAME="$(basename $(readlink -f $0))"

# The directory of containing this script
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# The install directory to the tools directory
INSTALL_DIR="$(dirname ${SCRIPT_DIR})/installed-tools/${TOOL_NAME}"


#################
### FUNCTIONS ###
#################



############
### MAIN ###
############

# Get arguments passed by qcr script, 
# Arguments passed are:
#   USE_CACHED
#   ARGS_TO_TOOL
USE_CACHED="${@:1:1}"
ARGS=( "${@:2}" )

# Source common
source $(dirname ${SCRIPT_DIR})/common

# Bail if git isn't found
git_command_exists

# Install tool, if required
install_tool ${REPO_CLONE_URL} ${INSTALL_DIR} ${TOOL_NAME}

# check if latest
if [ ${USE_CACHED} == false ]; then
    check_cloned_repo_is_latest ${INSTALL_DIR} ${TOOL_NAME}
fi
 
# Run <TOOL_NAME> tool with provided command and arguments
${INSTALL_DIR}/${TOOL_NAME}  "${ARGS[@]}"
