#!/bin/bash
# Author: Gavin Suddrey
# Version: 0.1.0

# Read Password
echo -n 'Cluster Admin Password: '
read -s PASSWORD
echo

CMD=$@

for machine in $(curl -s -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/qcr/gpu-cluster/main/machines); do 
    echo "Executing on $machine"
    
    if [ -f $1 ]; then 
      sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no administrator@$machine "bash -s" < $1
    else
      sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no administrator@$machine "$CMD"
    fi
done
