#!/bin/bash

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=AU/ST=QLD/L=Brisbane/O=QUT/OU=EER/CN=$HOSTNAME/emailAddress=robotics.ref@qut.edu.au"

openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

apt install -y nginx-full

cat <<EOF >>/etc/nginx/sites-available/panda-desktop
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        return 301 https://$HOSTNAME\$request_uri;
}

server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;

        server_name _;

        location / {
                proxy_pass https://172.16.0.2;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host \$host;
        }

        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
}
EOF

rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/panda-desktop /etc/nginx/sites-enabled/panda-desktop

service nginx restart

