#!/bin/bash

sudo apt install -y curl python3-pip

pip install git+https://github.com/qcr/gpuview.git@main

export PATH=$PATH:/home/$USER/.local/bin

gpuview service --port 8080 --table-only

CMD="update-cluster-machines"

curl -s -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/qcr/gpu-cluster/main/tools/update-cluster-machines > $HOME/.local/bin/$CMD

chmod +x $HOME/.local/bin/$CMD
$CMD

if [[ $(crontab -l 2>/dev/null | egrep -v "^(#|$)" | grep -q "$CMD"; echo $?) == 1 ]]
then
  set -f
  if [ "$(crontab -l 2>/dev/null)" != "" ]; then
    echo -e "$(crontab -l 2>/dev/null)\n\n*/1 * * * * PATH=$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $CMD" | crontab -
  else
    echo -e "*/30 * * * * PATH=$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $CMD" | crontab -
  fi
  set +f
fi

echo 'Finished'
